### ISSUE TITLE
Visibility for writeObject

### ISSUE THREAD

**Issue by samin** [thephpleague/flysystem-aws-s3-v2#4]
Global visibility parameter is not passed to
    protected function writeObject(array $options) on line 163 of AwsS3Adapter

I set the global parameter like this:
            return new League\Flysystem\Filesystem($adapter, null, array('visibility' => 'public'));

Is it me or is it missing?

**Comment by zaak** [comment]
The constructor of `League\Flysystem\Filesystem` was changed in new version.
Now it looks like:
`public function __construct(AdapterInterface $adapter, $config = null)`
Try passing config as a second parameter.

**Comment by frankdejonge** [comment]
@samin, the caching has moved to an adapter decorator, what @zaak mentions, moving the config one param up, is the solution.

**Comment by samin** [comment]
OK, will do. Have to change the docs, though:
http://flysystem.thephpleague.com/api/#global-visibility-setting
