### ISSUE TITLE
Filepath returned after fetching object points to non-existent file

### ISSUE THREAD

**Issue by FoxxMD** [thephpleague/flysystem-aws-s3-v2#9]
This is an odd one and, to be honest, I'm not even sure if this is the right place for this but it seems the most relevant.

I am using this package with Laravel 5.0. 

I have a [command](http://laravel.com/docs/5.0/bus) that handles files stores on s3. Using Laravel's [FileSystem](http://laravel.com/docs/5.0/filesystem)(FlySystem) with this package I obtain a file from s3:

`$s3Disk->get($fileLocation)`

The [returned value of this method](https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L215) is a string filepath to `private/var/temp/xxxxx`, which is the location of the file contents obtained from s3. 

This works as expected when my app is running [synchronously](http://laravel.com/docs/5.0/bus#dispatching-commands) and the command is executed when it is invoked, however when I use [queued commands](http://laravel.com/docs/5.0/bus#queued-commands) and instead execute these commands from a [listener](http://laravel.com/docs/5.0/queues#running-the-queue-listener) I get different behavior from FlySystem.

When run on a listener `$s3Disk->get($fileLocation)` still returns a filepath but **the file does not exist**. 

In case you are not familiar with Laravel's commands/queues the code that is being executed in context to FlySystem (in the command) is identical -- it doesn't matter if it's synchronous or run by a listener after fetching it from a queue, it's all the same code in a `handle()` method in the command.

Can anyone provide any insight into why this might happen? 

I have a hunch that it is caused by the context the application is running in (single process, synchronous request vs. listener where the app is a child process?) and somehow temporary files are being cleaned up immediately after creation but I really have no idea.

**Comment by frankdejonge** [comment]
@FoxxMD Hi, I'm trying to understand how this is happening. Perhaps you could setup a homestead box which reproduces this? That could give me the opportunity too dig into it instead of guessing what's going on. There's very little to go by without that.

**Comment by frankdejonge** [comment]
@FoxxMD ... I'm curious now, was there an issue? Or was it something unrelated to Flysystem?

**Comment by FoxxMD** [comment]
@frankdejonge So I'm super embarrassed. I wrote over the file with the temporary file name somewhere in my code and didn't realize it. I've been reading a file whose contents was literally just a filepath for hours now. 

Fairly certain the reason it works with sync is because I have to upload a new file for the process to kick off. When doing sqs I'm just running from the queue so it uses whatever the result of my code from the whole command is, which is clearly messed up somewhere. I've been in my own feedback loop xD I think it's time to go home.

**Comment by frankdejonge** [comment]
@FoxxMD haha, one of those days ey. Call it a day, there are more hours left to work in tomorrow ;)

**Comment by FoxxMD** [comment]
Yep, one of those days. I'm going to go crawl in a hole now haha :sob:
